# FILE     Makefile
# PACKAGE  RunIgnition
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for test programs of the "RunIgnition" package.
#
# COPYRIGHT (C) 1997 Cantera Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ..; pwd)


#I
include ../etc/Cantera/MakeDef


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
